include(`team/template.m4')dnl
FM_TEAM_BIO(`Gilda Gonzales', `CEO Unity Council, Oakland, CA', `directors',

`<p>Gilda Gonzales, Chief Executive Officer of the Unity Council, has a long history of public service.   Beginning in 1987, she was selected as a California State Assembly Fellow working in the California State Legislature.   Following her fellowship program, she worked on numerous state and national political campaigns then returned to the State Assembly as a Legislative Aide.   In 1991, she began her career in Oakland City Hall serving as Policy Analyst to former Mayor Elihu Harris.   During her fourteen year career in Oakland City Hall, she gained a vast knowledge in municipal financing and budgeting, public policy, economic development and government relations respectfully.   She served in several capacities from budget analyst, Special Assistant to the Finance Agency Director, Intergovernmental Affairs Director, and Chief of Staff to former City Manager Robert Bobb and Mayor Jerry Brown.</p>

<p>In the fall of 2004, Ms. Gonzales was named the Chief Executive Officer for the Unity Council.     She leads a forty-six year old organization comprised of 225 employees with an $18M annual budget and $70M in assets.   The Unity Council is a non-profit community development corporation committed to enriching the quality of life of families and individuals primarily in the Fruitvale District of Oakland.</p>

<p>In August 2009, she was nominated by Mayor Dellums and confirmed by the Oakland City Council to serve as a Port of Oakland Commissioner.   The Charter of the City of Oakland vests the Board of Port Commissioners with exclusive control and management of the Port.    Additionally, she serves on the Alameda County First Five Commission, State Farm Bank National CRA Advisory Board, and Bay Area Council Economic Institute Board of Trustees.</p>
<p>Originally from the Central Valley (Atwater), she attended and received a Bachelor&apos;s degree in Industrial Psychology from St. Mary&apos;s College (Moraga, CA), and a Master&amp;s of Public Administration from California State University, East Bay.   She and her husband, Ken Wysocki, Ph.D., reside in Oakland.</p>')
